apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: rashiweek10acr.azurecr.io/order_service:IMAGE_TAG_HERE
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/orders
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8000
            - name: CUSTOMER_SERVICE_URL
              value: http://customer-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8000
      targetPort: 8000
