name: CD - Deploy to Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RG_NAME: week10-rg
  AKS_NAME: week10-aks
  ACR_NAME: rashiweek10acr
  K8S_DIR: k8s

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials -g "$RG_NAME" -n "$AKS_NAME" --overwrite-existing

      # Resolve latest image tag (from frontend repo in ACR)
      - name: Resolve image tag from ACR (latest)
        id: tag
        shell: bash
        run: |
          TAG=$(az acr repository show-tags \
                -n "$ACR_NAME" --repository frontend \
                --top 1 --orderby time_desc -o tsv)
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Using tag: $TAG"

      # Replace IMAGE_TAG_HERE for all services in kustomization.yaml
      - name: Inject image tag into k8s manifests
        working-directory: ${{ env.K8S_DIR }}
        run: |
          sed -i "s/IMAGE_TAG_HERE/${{ steps.tag.outputs.tag }}/g" kustomization.yaml
          echo "==== kustomization.yaml ===="
          cat kustomization.yaml

      - name: Deploy to AKS
        shell: bash
        run: |
          kubectl apply -k "${K8S_DIR}"
          echo "--- Resources ---"
          kubectl get deploy,svc,pods

      - name: Wait for frontend rollout
        shell: bash
        run: |
          for svc in product-service order-service customer-service frontend; do
            echo "Waiting for rollout of $svc ..."
            kubectl rollout status deploy/$svc --timeout=180s || true
          done
          kubectl get svc -o wide
