name: CD - Deploy to Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  prod-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy manifests
        run: |
          kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/ -n prod

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/frontend -n prod --timeout=180s
          kubectl get services -n prod
